### PR TITLE
Sequence Diagram

### PR DESCRIPTION
**Pull request by omarfaruqe123**
Student1

### CODE REVIEW

**Comment by omarfaruqe123** [comment]
student2

**Comment by omarfaruqe123** [comment]
Student4

**Comment by omarfaruqe123** [comment]
Student5

**Comment by omarfaruqe123** [comment]
Student6

**Comment by omarfaruqe123** [comment]
Teacher

**Comment by omarfaruqe123** [comment]
Teacher

**Comment by omarfaruqe123** [comment]
Teacher2

**Comment by alrakibabdullah** [comment]
School Management System over view

**Pull request merged**
